name: Weekly spell cooldown update

on:
    schedule:
        - cron: '0 6 */1 * *'
    workflow_dispatch:

jobs:
    run:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v5
              with:
                python-version: '3.12'
            - name: Refresh files
              run: python get_spell_cooldowns.py --json --csv

            - name: Commit and push files
              run: |
                git config user.name "github-actions[bot]"
                git config user.email "github-actions[bot]@users.noreply.github.com"
                git add spell_cds.csv
                git add spell_cds.json
                git diff --staged --quiet || git commit -m "Updated data $(date -u +%Y-%m-%d)"
                git push
